apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../release/kubernetes-manifests.yaml

images:
  - name: gcr.io/google-samples/microservices-demo/adservice
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/adservice
    newTag: latest
  - name: gcr.io/google-samples/microservices-demo/cartservice
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/cartservice
    newTag: latest
  - name: gcr.io/google-samples/microservices-demo/checkoutservice
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/checkoutservice
    newTag: latest
  - name: gcr.io/google-samples/microservices-demo/currencyservice
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/currencyservice
    newTag: latest
  - name: gcr.io/google-samples/microservices-demo/emailservice
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/emailservice
    newTag: latest
  - name: gcr.io/google-samples/microservices-demo/frontend
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/frontend
    newTag: latest
  - name: gcr.io/google-samples/microservices-demo/paymentservice
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/paymentservice
    newTag: latest
  - name: gcr.io/google-samples/microservices-demo/productcatalogservice
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/productcatalogservice
    newTag: latest
  - name: gcr.io/google-samples/microservices-demo/recommendationservice
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/recommendationservice
    newTag: latest
  - name: gcr.io/google-samples/microservices-demo/shippingservice
    newName: <ACCOUNT_ID>.dkr.ecr.ca-central-1.amazonaws.com/online-boutique/shippingservice
    newTag: latest
